### ISSUE TITLE
MAX_LIFETIME matters?

### ISSUE THREAD

**Issue by Provinm** [shunsukeaihara/django-mysql-geventpool#1]
i'm a dev interested in this repo, and wanna to use this repo ,i installed version 0.2.4 and made some stress tests, it worked well.

but it didnot offer MAX_LIFETIME setting in 0.2.4, i read source code, found that before every commit , django-mysql-geventpool will exec `conn.ping()` to make sure the connection is usable.
think it is enough to prevent `Mysql connection gone away ` exception.

wanna to know does MAX_LIFETIME  parameter matters?  is it ok in prod env not using this.

**Comment by shunsukeaihara** [comment]
Infinite connections are not recommended due to the unfortunate reality of some leaks on the database.
I experimentally added this option to clean up data that are associated with a session in database by closing connection.
